### ISSUE TITLE
Fix for the new personalized tracks

### ISSUE THREAD

**Issue by KaindlJulian** [KaindlJulian/sc-theme#2]
```css
.sc-classic .trackItem.active, .sc-classic .trackItem.hover {
    background-color: #f2f2f2;
    ...
}
```

`https://soundcloud.com/discover/sets/personalized-tracks/...`
